There is an error in this problem: 
	- File path: ../../scripts/webwork/source/College_Physics_Urone/7.Work_Energy_and_Energy_Resources/7-03.Gravitational_Potential_Energy/NU_U17_07_03_006.md
	- Error: 'part4'


Traceback (most recent call last):
  File "process.py", line 63, in main
    pbs.process_question_pl(source_filepath)
  File "/Users/parsaimac/.pyenv/versions/3.8.5/lib/python3.8/site-packages/problem_bank_scripts/problem_bank_scripts.py", line 615, in process_question_pl
    q_type = parsed_q['header'][part]['type']
KeyError: 'part4'
